---
project_name: wwhrd
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  format: tar.gz
  files:
  - LICENSE*
  - README*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
