---
project_name: wwhrd
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  format: tar.gz
  files:
  - LICENSE*
  - README*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dockers:
  - image: frapposelli/wwhrd
    goos: linux
    goarch: amd64
    binary: wwhrd
    tag_templates:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - "v{{ .Major }}.{{ .Minor }}"
    - latest
