version: 2.0

shared: &shared
  working_directory: /go/src/github.com/frapposelli/wwhrd
  steps:
    - checkout
    - run: hack/coverage
    - run: go install -v github.com/frapposelli/wwhrd
    - run: wwhrd check
jobs:
  "golang-1.8":
    <<: *shared
    docker:
      - image: circleci/golang:1.8
  "golang-1.9":
    <<: *shared
    docker:
      - image: circleci/golang:1.9
  "golang-1.10":
    <<: *shared
    docker:
      - image: circleci/golang:1.10
  "golang-1.11":
    <<: *shared
    docker:
      - image: circleci/golang:1.11
  "golang-1.12":
    <<: *shared
    docker:
      - image: circleci/golang:1.12
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: ./.circleci/docker-login.sh
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - "golang-1.8"
      - "golang-1.9"
      - "golang-1.10"
      - "golang-1.11"
      - "golang-1.12"
  release:
    jobs:
      - release:
          context: docker-frapposelli
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/