name: Go
on: 
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Test on Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.11, 1.12, 1.13]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Use Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: run coverage
      run: |
        bash hack/coverage
    - name: Install and check
      run: |
        go build -mod=vendor -x
        bash -c "./wwhrd check"



